@HOST = http://localhost:3001
@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoicGVkcm9wIiwicmFuZG9tIjoiYjljZTg2ZTctYTc5Yy00M2UxLWEwMjktYzU2MDJmMDg0MTQ4IiwiaWF0IjoxNzMxMTIyMTMxLCJleHAiOjE3MzExNTA5MzF9.MnQRGdmO0b4MhQf7l2xNWz1tQFQ4PlQRj5sZER5pOSc

### Ruta para verificar si el token esta vigente aun
POST {{HOST}}/usuarios/verificar
Authorization: Bearer {{TOKEN}}

### Ruta para obtener los modulos
GET {{HOST}}/roles/modulos
Authorization: Bearer {{TOKEN}}

### Ruta para crear un nuevo rol
POST {{HOST}}/roles/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "rol": "ADMINISTRADOR",
    "permisos": [
        {
            "id_modulo": 1,
            "activo": true
        },
        {
            "id_modulo": 2,
            "activo": true
        },
        {
            "id_modulo": 3,
            "activo": true
        },
        {
            "id_modulo": 4,
            "activo": true
        },
        {
            "id_modulo": 5,
            "activo": true
        },
        {
            "id_modulo": 6,
            "activo": true
        },
        {
            "id_modulo": 7,
            "activo": true
        },
        {
            "id_modulo": 8,
            "activo": true
        },
        {
            "id_modulo": 9,
            "activo": true
        }
    ]
}

### Ruta para consultar los roles
GET {{HOST}}/roles/
Authorization: Bearer {{TOKEN}}

### Ruta para consultar un rol por ID
GET {{HOST}}/roles/8
Authorization: Bearer {{TOKEN}}

### Ruta para consultar los usuarios
GET {{HOST}}/usuarios/
Authorization: Bearer {{TOKEN}}

### Ruta para consultar usuario por codigo
GET {{HOST}}/usuarios/buscar?codigo=e0bc75eb-8292-4bec-9db1-0baadc18906c
Authorization: Bearer {{TOKEN}}

### Ruta para consultar usuario por nombre
GET {{HOST}}/usuarios/buscarnombre?nombre=Pedro
Authorization: Bearer {{TOKEN}}

### Ruta para crear un nuevo usuario
POST {{HOST}}/usuarios/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "nombre": "Luis Prueba",
  "usuario": "luisp",
  "correo": "luisp@gmail.com",
  "contrasenia": "123",
  "esta_activo": true,
  "id_rol": 8,
  "costo_hora": 135
}

### Ruta para modificar un usuario
PUT {{HOST}}/usuarios/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "nombre": "Juan Daniel",
    "usuario": "juand",
    "correo": "juand@gmail.com",
    "contrasenia": "123",
    "esta_activo": true,
    "id_rol": 8,
    "costo_hora": 125,
    "codigo_usuario": "393898b5-3f6b-4050-a755-5ec3b10f6aa9"
}

### Ruta para eliminar un usuario
DELETE {{HOST}}/usuarios/?id=02b3f5d4-830b-4d13-9e5e-9e9aea7954ce
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

### Ruta para crear un nuevo proyecto
POST {{HOST}}/proyectos/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "nombre": "Proyecto prueba",
  "descripcion": "Este es el primer proyecto registrado",
  "id_linea": 1,
  "costo_estimado": 15000,
  "fecha_inicio": "2024-11-01",
  "fecha_final": "2025-01-30",
  "activo": true,
  "id_usuario_lider": "e0bc75eb-8292-4bec-9db1-0baadc18906c"
}

### Ruta para consultar proyectos
GET {{HOST}}/proyectos/
Authorization: Bearer {{TOKEN}}

### Ruta para consultar proyectos por nombre
GET {{HOST}}/proyectos/nombre?nombre=Aplicacion
Authorization: Bearer {{TOKEN}}

### Ruta para consultar proyectos por id
GET {{HOST}}/proyectos/1
Authorization: Bearer {{TOKEN}}

### Ruta para consultar mis proyectos
GET {{HOST}}/proyectos/misproyectos
Authorization: Bearer {{TOKEN}}

### Ruta para modificar un proyecto
PUT {{HOST}}/proyectos/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "id_proyecto": 1,
  "nombre": "Proyecto prueba prueba",
  "descripcion": "Este es el primer proyecto registrado prueba",
  "id_linea": 1,
  "costo_estimado": 18000,
  "fecha_inicio": "2024-10-01",
  "fecha_final": "2025-02-15",
  "activo": false,
  "id_usuario_lider": "e0bc75eb-8292-4bec-9db1-0baadc18906c"
}

### Ruta para eliminar un proyecto
DELETE {{HOST}}/proyectos/?id=2
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

### Ruta para consultar lineas desarrollo
GET {{HOST}}/lineas/
Authorization: Bearer {{TOKEN}}

### Ruta para crear linea desarrollo
POST {{HOST}}/lineas/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "linea": "Prueba API"
}

### Ruta para crear linea desarrollo
PUT {{HOST}}/lineas/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "id_linea": 3,
    "linea": "PRUBEA API"
}

### Ruta para consultar asignar un usuario a una linea
POST {{HOST}}/lineas/usuariolinea
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "id_linea": 2,
    "id_usuario": "393898b5-3f6b-4050-a755-5ec3b10f6aa9"
}

### Ruta para eliminar usuario de linea de desarrollo
DELETE {{HOST}}/lineas/usuariolinea?id=3
Authorization: Bearer {{TOKEN}}

### Ruta para consultar linea por nombre
GET {{HOST}}/lineas/nombre?nombre=Aplicativo
Authorization: Bearer {{TOKEN}}

### Ruta para consultar linea por id
GET {{HOST}}/lineas/2
Authorization: Bearer {{TOKEN}}

### Ruta para consultar los usuarios de cada linea
GET {{HOST}}/lineas/usuarioslineas
Authorization: Bearer {{TOKEN}}

### Ruta para consultar los usuarios de una linea
GET {{HOST}}/lineas/usuarioslinea?id=2
Authorization: Bearer {{TOKEN}}

### Ruta para consultar los usuarios de una linea
POST {{HOST}}/auth/
Content-Type: application/json

{
    "username": "pedrop",
    "password": "123"
}

### Ruta para registrar una tarea
POST {{HOST}}/tareas/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "id_proyecto": 2,
    "nombre_tarea": "Tarea de prueba algo",
    "descripcion_tarea": "Primera tarea creada algo",
    "id_estado": 2,
    "fecha_inicio": "2024-11-01",
    "fecha_finalizacion": "2424-11-05"
}

### Ruta para actualizar una tarea
PUT {{HOST}}/tareas/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "id_tarea": 2,
  "id_proyecto": 1,
  "nombre_tarea": "Tarea actualizada",
  "descripcion_tarea": "Descripcion actualizada",
  "id_estado": 2,
  "fecha_inicio": "2024-11-15",
  "fecha_finalizacion": "2024-11-28"
}

### Ruta para eliminar una tarea
DELETE {{HOST}}/tareas/?id=4
Authorization: Bearer {{TOKEN}}

### Ruta para traer las tareas del usuario
GET {{HOST}}/tareas/
Authorization: Bearer {{TOKEN}}

### Ruta para actualizar el estado de una tarea a EN CURSO
PUT {{HOST}}/tareas/curso?id=2
Authorization: Bearer {{TOKEN}}

### Ruta para actualizar el estado de una tarea a EN CURSO
PUT {{HOST}}/tareas/completada?id=2
Authorization: Bearer {{TOKEN}}

### Ruta para obtener tareas del usuario agrupadas por estado
GET {{HOST}}/tareas/agrupadas
Authorization: Bearer {{TOKEN}}

### Ruta para obtener una tarea por id
GET {{HOST}}/tareas/unica?id=2
Authorization: Bearer {{TOKEN}}

### Ruta para registrar una hora de trabajo
POST {{HOST}}/tareas/hora
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "id_proyecto": 1,
  "horas_trabajadas": 8,
  "fecha_trabajada": "2024-11-04"
}

### Ruta para consultar las horas registradas del usuario
GET {{HOST}}/tareas/hora
Authorization: Bearer {{TOKEN}}

### Ruta para consultar las horas registradas del usuario
GET {{HOST}}/tareas/horaproyecto?id=2
Authorization: Bearer {{TOKEN}}

### Ruta para registrar una caso de prueba
POST {{HOST}}/pruebas/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "id_proyecto": 2,
  "nombre_caso": "Primer Caso de prueba Pedro",
  "descripcion_caso": "Descipción del primer caso de prueba de Pedro",
  "criterios_aceptacion": "Debe de retornar una JSON",
  "prueba_automatizada": {
    "estado_esperado": 200,
    "campos": [
        {
            "tipo_dato": 1,
            "nombre_campo": "nombre",
            "contenido": "pedro"
        },
        {
            "tipo_dato": 1,
            "nombre_campo": "apellido",
            "contenido": "juan"
        }
    ]
  }
}

### Ruta para registrar un error
POST {{HOST}}/pruebas/error
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "id_caso_prueba": 3,
  "descripcion": "Este es un error controlado 3",
  "id_usuario_asignado": "393898b5-3f6b-4050-a755-5ec3b10f6aa9",
  "fecha_reporte": "2024-11-20"
}

### Ruta para modificar un error
PUT {{HOST}}/pruebas/error
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "id_error": 2,
  "resuelto": false
}

### Ruta para obtener mis casos de prueba
GET {{HOST}}/pruebas/casos
Authorization: Bearer {{TOKEN}}

### Ruta para obtener mis errores asignados
GET {{HOST}}/pruebas/errores
Authorization: Bearer {{TOKEN}}

### Ruta para obtener un caso de prueba
GET {{HOST}}/pruebas/3
Authorization: Bearer {{TOKEN}}

### Ruta para obtener un caso de prueba
PUT {{HOST}}/pruebas/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "id_prueba_automatizada": 1,
  "cuerpo_devuelto": "Cuerpo devuelto",
  "estado_devuelto": 200,
  "correcto": true
}

### 
GET {{HOST}}/roles/modulos
Authorization: Bearer {{TOKEN}}
