INSERT INTO modulos(modulo) VALUES ('MI-AGENDA'),('MI-TABLERO'),('BACKLOG'),('PRUEBAS'),('PROYECTOS'),
('LINEAS-DESARROLLO'),('ESTADISTICAS'),('USUARIOS'),('ROLES');

INSERT INTO roles(rol) VALUES('ADMIN'),('SR'),('JR');